apply plugin: 'com.android.library'
apply plugin: 'com.google.devtools.ksp'
apply from: rootProject.file('gradle/module-api.gradle')

android {
    namespace 'net.kelmer.correostracker.dataApi'
}

dependencies {
    ksp libs.androidx.room.compiler
    implementation libs.androidx.room.runtime
    implementation libs.moshi.core
    implementation libs.moshi.reflect
}
